name: Docker Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and run Docker container1
      run: |
        docker build -t debian-iproute2 -f Dockerfile1 .
        docker run -d --name iproute2-container debian-iproute2 /bin/ss -tulpn > output.txt

    - name: Build and run Docker container2
      run: |
        docker build -t http-server -f Dockerfile2 .
        docker run -d --name http-server-container -p 9000:9000 http-server

    - name: Copy output.txt artifact
      run: docker cp iproute2-container:/output.txt .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: output.txt
